- name: configure code server
  hosts: code-server
  tasks:
  - name: update password
    lineinfile:
      path: "/lib/systemd/system/code-server.service"
      regexp: __PLACEHOLDER__
      line: "Environment=PASSWORD={{cs_password}}"
  - name: update domain
    lineinfile:
      path: "/etc/nginx/sites-available/code-server.conf"
      regexp: __PLACEHOLDER__
      line: "server_name {{cs_domain}};"
  - name: restart
    systemd:
      daemon-reload: yes
      name: "{{item}}"
      state: restarted
    loop:
      - code-server
      - nginx
